apiVersion: v1
kind: Service
metadata:
  labels:
    app: registration-deployment
  name: registration-service
  namespace: ckad
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: registration-deployment
